spring:
  application:
    name: gestionempleados
  datasource:
    url: jdbc:mysql://localhost:3306/CASTOR_TEST
    username: samuel
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update